version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - '3001:3000'
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: next-frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env.local
    restart: unless-stopped
