version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres17_integration_studio
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: postgres
      POSTGRES_DB: lanchonete
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - integration_network

  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - '3001:3000'
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - integration_network

  frontend:
    build: ./frontend
    container_name: next-frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env.local
    restart: unless-stopped
    networks:
      - integration_network

volumes:
  postgres_data:

networks:
  integration_network:
